name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install test dependencies first
        pip install pytest pytest-cov
        # Install package dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install package in editable mode
        pip install -e .
        
    - name: Configure JAX for CPU
      run: |
        echo "JAX_PLATFORMS=cpu" >> $GITHUB_ENV
        
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ --cov=qem --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
